Revert some changes from PDK-1004
Rather than going through Puppets exception logger, uses the BaseContext log_exception function.  This provides better stack trace information and a clearer indication of where the exception was raised:

Before:

Error: #<Puppet::ResourceApi::PuppetContext::LoggingProxy:0x00007fec9fd90268>: Failed after 0.000160 seconds

After:

Error: user_admin[bob]: Updating: Failed after 0.000152 seconds: Role based administrator type missing `role_profile` attribute